feat: specify custom run command
leancloud/django-getting-started pull request #14
Opened 2021-06-11 03:34 UTC by cshuaimin

Specify how to start the project in `leanengine.yaml`'s `run` field.

2021-06-11 08:13 UTC, weakish requested changes

2021-06-11 08:13 UTC, weakish commented on wsgi.py
> +from geventwebsocket.handler import WebSocketHandler
貌似 Django 是没有依赖 gevent-websocket，然后 leancloud 也只依赖了 gevent，所以 requirements.txt 需要加下 gevent-websocket 这个依赖。

2021-06-11 08:13 UTC, weakish commented on wsgi.py
> +    server = WSGIServer(('', PORT), application, handler_class=WebSocketHandler)
这里也要和 flask 模板项目一样处理下请求日志的问题（云引擎在负载均衡层面收集了请求日志，所以要关掉。本地就开着，方便本地调试）。

2021-06-15 03:22 UTC, cshuaimin commented on wsgi.py
> +    server = WSGIServer(('', PORT), application, handler_class=WebSocketHandler)
在指定了 `handler_class=WebSocketHandler` 后，`gevent.pywsgi.WSGIServer` 原本的输出日志方式会失效：https://github.com/gevent/gevent/issues/1432 。也就是说 Flask 原来的代码在本地运行时也是没有请求日志的；Django 版由于之前没有指定 `handler_class=WebSocketHandler` 所以有日志，但是这次指定后也就没有日志了……

2021-06-15 04:33 UTC, weakish commented on wsgi.py
> +    server = WSGIServer(('', PORT), application, handler_class=WebSocketHandler)
竟然是这样……

2021-06-15 04:34 UTC, weakish commented on wsgi.py
> +    server = WSGIServer(('', PORT), application, log=log, handler_class=WebSocketHandler)
这里监听地址也要改下，本地用 localhost

2021-06-15 06:06 UTC, cshuaimin commented on wsgi.py
> +    server = WSGIServer(('', PORT), application, log=log, handler_class=WebSocketHandler)
好了

2021-06-15 06:39 UTC, weakish approved these changes

2021-06-25 10:34 UTC, weakish commented
本地 `lean deploy` 测了一下没问题

2021-06-25 10:34 UTC, merged